Mention {mirai} in {future} docs
rstudio/promises pull request #111
Opened 2024-11-25 23:10 UTC by jcheng5

Sorry @shikokuchuo, I just realized I had these changes sitting locally, uncommitted. I thought I had published this ages ago.

2024-11-26 00:04 UTC, shikokuchuo commented
Thanks Joe!

My first thoughts on those bullets are:

3. `mirai` actually has a general interface for launching remote workers and is being used on Slurm clusters, for example this [community-contributed example](https://shikokuchuo.net/mirai/articles/mirai.html#cluster-resource-managers). I know that future is designed to be a general API, but I'm not sure that actually translates into it being able to be used in more places.
4. I think the key here is that `mirai` is queued, so nested topologies automatically work without having to carefully manage them like future - so this is definitely a positive for `mirai`, but doesn't quite read as such!

I also think it's definitely worth mentioning that:
-  `mirai` promises are event-driven rather than polling (much more efficient, lower latency)

The following may tie into 4 above, that `mirai` is inherently queued:
- `mirai` is always non-blocking and doesn't require the use of `future_promise()`

Hope the above makes sense for you. I'd be happy to suggest wording, but I also don't want to put words in your mouth! Let me know what you prefer or if you have any questions on the above.

2024-11-26 03:21 UTC, jcheng5 commented
Please feel free to edit. I don't even know what I wrote, this was months ago!

2024-11-26 10:22 UTC, shikokuchuo commented
> Please feel free to edit. I don't even know what I wrote, this was months ago!

Thanks Joe, I've gone ahead and added suggestions. Please feel free to re-word any of them. If there's anything I can make clearer for you do feel free to ask!

2024-11-26 10:23 UTC, shikokuchuo requested changes

2024-11-26 10:23 UTC, shikokuchuo commented on vignettes/promises_04_futures.Rmd
> +1. The `future` package tries hard to automatically infer what variables and packages you need from the main R package, and makes those available to the child process. `mirai` doesn't try to do this
```suggestion
1. The `future` package tries hard to automatically infer what variables and packages you need from the main R package, and makes those available to the child process. `mirai` doesn't try to do this for you; you need to pass in whatever data you need explicitly, and make package-namespaced calls explicitly inside of your inner code.
```

2024-11-26 10:23 UTC, shikokuchuo commented on vignettes/promises_04_futures.Rmd
> +1. The `future` package tries hard to automatically infer what variables and packages you need from the main R package, and makes those available to the child process. `mirai` doesn't try to do this
I know `library()` is probably clearer as a concept, but it's not good practice for users to be actually doing that inside a `mirai()` call!

2024-11-26 10:23 UTC, shikokuchuo commented on vignettes/promises_04_futures.Rmd
> +2. `mirai` is very fast; it's much faster than `future` at starting up and has less per-task overhead.
```suggestion
2. `mirai` is very fast; it's much faster than `future` at starting up and has less per-task overhead. `mirai` creates event-driven promises, whereas promises using `future` time-poll every 0.1 seconds. This makes `mirai` ideal where response times and latency are critical.
```

2024-11-26 10:23 UTC, shikokuchuo commented on vignettes/promises_04_futures.Rmd
> +3. `future` is designed to be a general API for managing distributed programming across many types of computing backends. `mirai` is more narrowly scoped: it does support both local and distributed e
```suggestion
3. `future` is designed to be a general API supporting many types of distributed computing backends, and potentially offers more options. `mirai` on the other hand is its own system, whilst it does support both local and distributed execution.
```

2024-11-26 10:23 UTC, shikokuchuo commented on vignettes/promises_04_futures.Rmd
> +4. `future` puts a big emphasis on complicated scenarios where futures launch other futures ("evaluation topologies"); mirai doesn't care about this.
```suggestion
4. `mirai` is inherently queued, meaning it readily accepts more tasks than workers. This means you don’t need an equivalent of `future_promise()`. With `future` you need to manage cases where futures launch other futures ("evaluation topologies") upfront, whereas with `mirai` they will just work.
```

2024-11-26 10:23 UTC, shikokuchuo commented on vignettes/promises_04_futures.Rmd
> +While this article and others on this site focus on the `future` package, there's an up and coming package called [`mirai`](https://shikokuchuo.net/mirai/) that you may want to consider instead.
```suggestion
While this article and others on this site focus on the `future` package, there's a much newer package called [`mirai`](https://shikokuchuo.net/mirai/) that you may want to consider instead.
```

2025-01-10 10:57 UTC, shikokuchuo commented on vignettes/promises_04_futures.Rmd
> +</div>
```suggestion
5. `mirai` supports task cancellation and the ability to interrupt ongoing tasks on the worker.
</div>
```

2025-01-10 10:59 UTC, shikokuchuo commented
@jcheng5 I've added a final point about task cancellation. It would be good to get this merged. Thanks!

2025-02-10 17:32 UTC, merged

2025-02-11 16:42 UTC, jcheng5 commented
Took some messing around with the version number (initially the updated docs only went to the /dev/ URL path), but it's updated now.

2025-02-11 17:46 UTC, shikokuchuo commented
Thanks!